# Generated by Django 3.2.4 on 2021-10-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Desc',
            field=models.TextField(),
        ),
    ]
